name: Remove Duplicate URLs

on:
  push:
    branches:
      - master
    paths:
      - 1.txt

jobs:
  remove_duplicates:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Remove duplicate URLs
        run: |
          # 在这个步骤中，你可以使用适当的命令或脚本来执行去重操作
          # 假设使用一个名为"remove_duplicates.js"的JavaScript脚本来去重URL
          node remove_duplicates.js 1.txt 2.txt
